networks:
  postgres:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_db
        SPRING_DATASOURCE_USERNAME: ${YOUR_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${YOUR_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8081:8080"
      - "5005:5005"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${YOUR_USERNAME}
      POSTGRES_PASSWORD: ${YOUR_PASSWORD}
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
